spring:
  application:
    name: auth-service
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

