spring:
  application:
    name: gateway

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: false

  cloud:
    gateway:
      routes:
        # Auth Login
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: login-service
          uri: lb://login-service
          predicates:
            - Path=/login-service/**

        # Service
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1

        - id: item-service
          uri: lb://item-service
          predicates:
            - Path=/item-service/**

        - id: lot-service
          uri: lb://lot-service
          predicates:
            - Path=/lot-service/**

        - id: supplier-service
          uri: lb://supplier-service
          predicates:
            - Path=/supplier-service/**

        - id: category-service
          uri: lb://category-service
          predicates:
          - Path=/category-service/**

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory-service/**

        # BFF
        - id: item-bff
          uri: lb://item-bff
          predicates:
            - Path=/item-bff/**

        - id: inventory-bff
          uri: lb://inventory-bff
          predicates:
            - Path=/inventory-bff/**



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka