spring:
  application:
    name: gateway

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: false

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: login-service
          uri: lb://login-service
          predicates:
            - Path=/login-service/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1
#        - id:
#          uri:
#          predicates:
#            -
        - id: item-service
          uri: lb://item-service
          predicates:
            - Path=/item-service/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory-service/**
        - id: inventory-bff
          uri: lb://inventory-bff
          predicates:
            - Path=/inventory-bff/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka