spring:
  application:
    name: authService
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
  datasource:
    url: jdbc:postgresql://localhost:5432/mosaicerp
    username: mosaic
    password: mosaic
    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8081

