spring:
  application:
    name: login-service
  datasource:
    url: jdbc:postgresql://localhost:5432/mosaicerp
    username: mosaic
    password: mosaic

server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka