name: Build and Test outbound Service

on:
  push:
    paths:
      - 'api-gateway/**'
      - '.github/workflows/api-gateway.yml'

jobs:
  build-gateway:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api-gateway

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build